# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: xdlmost's Blog
email: xdeliver@163.com
description: >- # this means to ignore newlines until "baseurl:"
    record steps to the future 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xdlmost.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  xdlmost

# Build settings
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /:year/:month/:title
paginate: 3